application: snail-test
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /
  script: snail-test.app

- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: latest
